import Head from "next/head"
import {DatePicker} from 'antd'

export default function () {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                
            </main>
        </>     
    );
}