import Head from "next/head"
import { ReactElement } from "react";
import AuthenticationLayout from "../../layouts/AuthenticationLayout";
import { NextPageWithLayout } from "../_app";

const LoginPage: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                Here is login page
            </main>
        </>     
    );
}

LoginPage.getLayout = function getLayout(page: ReactElement){
    return(
        <AuthenticationLayout>
            {page}
        </AuthenticationLayout>
    )
}

export default LoginPage;