import Head from 'next/head'
import { ReactElement } from 'react'
import styled from 'styled-components'
import HomeLayout from '../layouts/HomeLayout'
import { NextPageWithLayout } from './_app'

const HomePage: NextPageWithLayout = () => {
  return (
      <>
          <Head>
              <title>Home page</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
              Here is home page
      </>     
  );
}

HomePage.getLayout = function getLayout(page: ReactElement){
  return(
      <HomeLayout>
          {page}
      </HomeLayout>
  )
}

export default HomePage;
